# This provides us with GCC binary support so we can run bash
language: generic

sudo: required

script:
  - ./build.sh
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/aptRepoUpdater.sh; fi'

before_deploy:
  - export image_name="`echo *.iso`"
  - cat *.iso > "/home/travis/${image_name}"

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "IBOHja2Ip9Zo0slYX12Ce8vYSiypw7frU8Wbn00ZIaGP+dWW6G1FP+Weo6ai4OnX9LMoxQtc1842rfq84N/yw8mFElB3EICJe+yjGzijINf56RW1EhQtrdbok/K95OiS8XNZtXh9hr+a3IX7f4ZtaydFALRcOUgR8gCJFkkujT6/+5VzeEefyYg6+JMz6jU2S9EGmows/UtR1Zo+2KnCKgMH89i9l/9kY+w+Z5vBYqEXx4xx623dzVkhln54Wz7VwEzK4I1kvy+kjy1X4NUQNI6JMKOEjsNZ4TUfR0VWKhKTVRt/E0UV6m6LFtvhwg9KYNb96/Sq3SUM5B9nVcwNvL+ZFOzYFxqCgwhtAn6UAhEoK8C292XPbaDbwc4qtm3RyX7tJ44+K2b060ZPkG0bc90ypvPxaBkHwYoY3r0oiOofCYnFnArc5zq6DaxeJE1+bMfVC14hr+lhPGLQ1uxb+FZ7r49Wt8U6kfgB+mpuW+/3YnNxeuOV+NzDWlQAIaBs0qGSD8ucAcUtb0pDaM52fZLtMwqiyMHd/rvcbiFT4DVoII3BRFFWyxRSiMQRGBnz+LkG+YORPv6PIJpnfcPNLXiqB6ndEkBUcmfnHkVs0B6cf2IGcICMN4rdIGW/v/EeT2E0+/C3Cf07CiPfZe7xedJfczlJeikmYsJpylm8HeI="
    file_glob: true # http://stackoverflow.com/a/28579635/1320237
    file: "/home/travis/${image_name}"
    on:
      branch: master
