language: generic
sudo: required
script:
- "./build.sh"
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/aptRepoUpdater.sh;
  fi
after_success:
 - export image_name="`echo *.iso`"
 - cat *.iso > "/home/travis/${image_name}"
 - curl -u $ftplogin:$ftppassword -T /home/travis/${image_name} https://dav.box.com/dav/
notifications:
  email:
  - $email
